### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by heddesheimer** [helhum/TYPO3-Distribution#17] opened 2018-05-10 07:48 UTC
Hi,
I tried the installation but getting this. What am I missing?

Setting up TYPO3

Check environment / create folders:
OK

Connect to database:
User name for database server (default: ""):
User password for database server:

  [TYPO3\CMS\Core\Error\Exception]
  Warning: copy(phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Helper/../Resources/bin/
  hiddeninput.exe): failed to open stream: phar error: "vendor/symfony/console/Resources/bin/hiddeninput.exe" is not
  a file in phar "C:/ProgramData/ComposerSetup/bin/composer.phar" in phar://C:/ProgramData/ComposerSetup/bin/composer
  .phar/vendor/symfony/console/Helper/QuestionHelper.php line 330

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

**Comment by helhum** [comment] 2018-05-12 15:32
That obviously seems to be an error in your composer.phar or within the embedded Symfony component. What is the composer version you are using?

**Comment by heddesheimer** [comment] 2018-05-12 15:39
I just installed a fresh composer version for Windows. It says it's version 1.6.5

**Comment by helhum** [comment] 2018-05-12 16:08
As far as I can see, the issue is that composer.phar does not include this file. I opened a ticket in composer issue tracker

**Comment by heddesheimer** [comment] 2018-05-12 17:10
Thank you. So all I can do is to wait until they fixed it?

**Comment by helhum** [comment] 2018-05-12 17:19
You could try installing from git bash instead. Could work.

Or put a file `.installed` next to the `composer.json` of this distribution,
which skips the install during composer install. And then do `vendor/bin/typo3cms install:setup`.

**Comment by helhum** [comment] 2019-11-18 17:07
fixed in Composer a long time ago.

**Closed as completed by helhum** 2019-11-18 17:07 UTC
